# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0004_auto_20170413_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statue',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
