# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0005_auto_20170425_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statue',
            name='pictures',
            field=models.ImageField(default='example_app/static/img/no-img.png', upload_to='example_app/static/img'),
        ),
    ]
