# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0006_auto_20170512_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=32),
        ),
    ]
