# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0007_beacon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statue',
            name='pictures',
            field=models.ImageField(default='pic_folder/no-img.png', upload_to='pic_folder/'),
        ),
    ]
