# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0008_auto_20170602_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='slug_statue',
            field=models.SlugField(default='', max_length=32),
        ),
    ]
