# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0009_beacon_slug_statue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='slug_statue',
        ),
    ]
