# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0010_remove_beacon_slug_statue'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='slug_statue',
            field=models.SlugField(blank=True, default='', max_length=32),
        ),
    ]
